
# Email Configuration (Optional)
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USER = "manaswikotha3112@gmail.com"
EMAIL_PASSWORD = "tyax iiav tdtw phuz"

# App Settings
APP_ENV = "production"